//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TachoResources.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TachoResources.Properties.Resources.ru", typeof(Resources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AboutTechService {
            get {
                return ResourceManager.GetString("AboutTechService", resourceCulture);
            }
        }
        
        internal static string ActivateText {
            get {
                return ResourceManager.GetString("ActivateText", resourceCulture);
            }
        }
        
        internal static string ActivationRemootSeveceText {
            get {
                return ResourceManager.GetString("ActivationRemootSeveceText", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        internal static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        internal static string Do_you_have_a_license_file {
            get {
                return ResourceManager.GetString("Do_you_have_a_license_file", resourceCulture);
            }
        }
        
        internal static string Enter_the_registration_number_of_the_license {
            get {
                return ResourceManager.GetString("Enter_the_registration_number_of_the_license", resourceCulture);
            }
        }
        
        internal static string GetLicenceText {
            get {
                return ResourceManager.GetString("GetLicenceText", resourceCulture);
            }
        }
        
        internal static string Have_You_File_Licence {
            get {
                return ResourceManager.GetString("Have_You_File_Licence", resourceCulture);
            }
        }
        
        internal static string HelpTextForOfflineregistration {
            get {
                return ResourceManager.GetString("HelpTextForOfflineregistration", resourceCulture);
            }
        }
        
        internal static string HelpTextForUpdateService {
            get {
                return ResourceManager.GetString("HelpTextForUpdateService", resourceCulture);
            }
        }
        
        internal static string IDText {
            get {
                return ResourceManager.GetString("IDText", resourceCulture);
            }
        }
        
        internal static string IPARCText {
            get {
                return ResourceManager.GetString("IPARCText", resourceCulture);
            }
        }
        
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        internal static string LicenceText {
            get {
                return ResourceManager.GetString("LicenceText", resourceCulture);
            }
        }
        
        internal static string License_file_verification_failed {
            get {
                return ResourceManager.GetString("License_file_verification_failed", resourceCulture);
            }
        }
        
        internal static string LicSerilaNumberText {
            get {
                return ResourceManager.GetString("LicSerilaNumberText", resourceCulture);
            }
        }
        
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static string OfflineText {
            get {
                return ResourceManager.GetString("OfflineText", resourceCulture);
            }
        }
        
        internal static string OnlineText {
            get {
                return ResourceManager.GetString("OnlineText", resourceCulture);
            }
        }
        
        internal static string ParamsText {
            get {
                return ResourceManager.GetString("ParamsText", resourceCulture);
            }
        }
        
        internal static string PortNumberText {
            get {
                return ResourceManager.GetString("PortNumberText", resourceCulture);
            }
        }
        
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        internal static string Select_the_registration_method {
            get {
                return ResourceManager.GetString("Select_the_registration_method", resourceCulture);
            }
        }
        
        internal static string Select_the_update_method {
            get {
                return ResourceManager.GetString("Select_the_update_method", resourceCulture);
            }
        }
        
        internal static string ServiceNonActive {
            get {
                return ResourceManager.GetString("ServiceNonActive", resourceCulture);
            }
        }
        
        internal static string TachoServiceDescriptionText {
            get {
                return ResourceManager.GetString("TachoServiceDescriptionText", resourceCulture);
            }
        }
        
        internal static string To_activate_you_need_a_license_file {
            get {
                return ResourceManager.GetString("To_activate_you_need_a_license_file", resourceCulture);
            }
        }
        
        internal static string UntilText {
            get {
                return ResourceManager.GetString("UntilText", resourceCulture);
            }
        }
        
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        internal static string Text_Logo {
            get {
                return ResourceManager.GetString("Text_Logo", resourceCulture);
            }
        }
        
        internal static string HelpTextForOnlineregistration {
            get {
                return ResourceManager.GetString("HelpTextForOnlineregistration", resourceCulture);
            }
        }
        
        internal static string InvalidSerialNumberError {
            get {
                return ResourceManager.GetString("InvalidSerialNumberError", resourceCulture);
            }
        }
        
        internal static string LicenceNotMatch {
            get {
                return ResourceManager.GetString("LicenceNotMatch", resourceCulture);
            }
        }
        
        internal static string ValideDateDescription {
            get {
                return ResourceManager.GetString("ValideDateDescription", resourceCulture);
            }
        }
        
        internal static string LicenceRequestSuccesfull {
            get {
                return ResourceManager.GetString("LicenceRequestSuccesfull", resourceCulture);
            }
        }
        
        internal static string LicenceRequestUnSuccesfull {
            get {
                return ResourceManager.GetString("LicenceRequestUnSuccesfull", resourceCulture);
            }
        }
        
        internal static string notyfication_needstatephone {
            get {
                return ResourceManager.GetString("notyfication_needstatephone", resourceCulture);
            }
        }
        
        internal static string RequestForReadPhoneStateError {
            get {
                return ResourceManager.GetString("RequestForReadPhoneStateError", resourceCulture);
            }
        }
        
        internal static string RequestRWExternalStorageError {
            get {
                return ResourceManager.GetString("RequestRWExternalStorageError", resourceCulture);
            }
        }
        
        internal static string UserSelectModeActivationError {
            get {
                return ResourceManager.GetString("UserSelectModeActivationError", resourceCulture);
            }
        }
        
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        internal static string FileNotSavedText {
            get {
                return ResourceManager.GetString("FileNotSavedText", resourceCulture);
            }
        }
        
        internal static string LicFileSavedText {
            get {
                return ResourceManager.GetString("LicFileSavedText", resourceCulture);
            }
        }
        
        internal static string notyfication_needrwstorage {
            get {
                return ResourceManager.GetString("notyfication_needrwstorage", resourceCulture);
            }
        }
        
        internal static string HelpTextForChooseFileOnDevice {
            get {
                return ResourceManager.GetString("HelpTextForChooseFileOnDevice", resourceCulture);
            }
        }
        
        internal static string HelpTextForNewLicence {
            get {
                return ResourceManager.GetString("HelpTextForNewLicence", resourceCulture);
            }
        }
        
        internal static string HelpTextForNewLicenceError {
            get {
                return ResourceManager.GetString("HelpTextForNewLicenceError", resourceCulture);
            }
        }
        
        internal static string UserSelectLicFileTextForAcivate {
            get {
                return ResourceManager.GetString("UserSelectLicFileTextForAcivate", resourceCulture);
            }
        }
        
        internal static string UserSelectLicFileTextForUpdate {
            get {
                return ResourceManager.GetString("UserSelectLicFileTextForUpdate", resourceCulture);
            }
        }
        
        internal static string ErrorSerialNumber {
            get {
                return ResourceManager.GetString("ErrorSerialNumber", resourceCulture);
            }
        }
        
        internal static string Licence_not_activated {
            get {
                return ResourceManager.GetString("Licence_not_activated", resourceCulture);
            }
        }
        
        internal static string SaveRegFileError {
            get {
                return ResourceManager.GetString("SaveRegFileError", resourceCulture);
            }
        }
        
        internal static string CantReadRegFile {
            get {
                return ResourceManager.GetString("CantReadRegFile", resourceCulture);
            }
        }
        
        internal static string LicenceCheckError {
            get {
                return ResourceManager.GetString("LicenceCheckError", resourceCulture);
            }
        }
        
        internal static string ErrorRepportSavedText {
            get {
                return ResourceManager.GetString("ErrorRepportSavedText", resourceCulture);
            }
        }
    }
}
